# vim:ft=kitty
## name: Teide Darker
## author: OpenCode Theme
## blurb: Darker variant of the Teide color scheme

foreground                      #E7EAEE
background                      #171B20
selection_foreground            #E7EAEE
selection_background            #2f3546

cursor                          #5CCEFF
cursor_text_color               #171B20

url_color                       #0AE7FF

active_border_color             #5CCEFF
inactive_border_color           #414868
bell_border_color               #F97791
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #171B20
active_tab_foreground           #E7EAEE
inactive_tab_background         #111418
inactive_tab_foreground         #a9b1d6
tab_bar_background              #111418
tab_bar_margin_color            none

mark1_foreground                #171B20
mark1_background                #5CCEFF
mark2_foreground                #171B20
mark2_background                #FFE77A
mark3_foreground                #171B20
mark3_background                #F97791

#: black
color0                          #414868
color8                          #586172

#: red
color1                          #F97791
color9                          #F73F64

#: green
color2                          #38FFA5
color10                         #41FFDC

#: yellow
color3                          #FFA064
color11                         #FFE77A

#: blue
color4                          #5CCEFF
color12                         #89BEFF

#: magenta
color5                          #B2A3FF
color13                         #FFB3EC

#: cyan
color6                          #0AE7FF
color14                         #00FBFF

#: white
color7                          #a9b1d6
color15                         #E7EAEE
